// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadHello_file_ring_buffer returns the embedded CollectionSpec for hello_file_ring_buffer.
func loadHello_file_ring_buffer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Hello_file_ring_bufferBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load hello_file_ring_buffer: %w", err)
	}

	return spec, err
}

// loadHello_file_ring_bufferObjects loads hello_file_ring_buffer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*hello_file_ring_bufferObjects
//	*hello_file_ring_bufferPrograms
//	*hello_file_ring_bufferMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadHello_file_ring_bufferObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadHello_file_ring_buffer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// hello_file_ring_bufferSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type hello_file_ring_bufferSpecs struct {
	hello_file_ring_bufferProgramSpecs
	hello_file_ring_bufferMapSpecs
	hello_file_ring_bufferVariableSpecs
}

// hello_file_ring_bufferProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type hello_file_ring_bufferProgramSpecs struct {
	CaptureOpenat *ebpf.ProgramSpec `ebpf:"capture_openat"`
}

// hello_file_ring_bufferMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type hello_file_ring_bufferMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// hello_file_ring_bufferVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type hello_file_ring_bufferVariableSpecs struct {
}

// hello_file_ring_bufferObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadHello_file_ring_bufferObjects or ebpf.CollectionSpec.LoadAndAssign.
type hello_file_ring_bufferObjects struct {
	hello_file_ring_bufferPrograms
	hello_file_ring_bufferMaps
	hello_file_ring_bufferVariables
}

func (o *hello_file_ring_bufferObjects) Close() error {
	return _Hello_file_ring_bufferClose(
		&o.hello_file_ring_bufferPrograms,
		&o.hello_file_ring_bufferMaps,
	)
}

// hello_file_ring_bufferMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadHello_file_ring_bufferObjects or ebpf.CollectionSpec.LoadAndAssign.
type hello_file_ring_bufferMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *hello_file_ring_bufferMaps) Close() error {
	return _Hello_file_ring_bufferClose(
		m.Events,
	)
}

// hello_file_ring_bufferVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadHello_file_ring_bufferObjects or ebpf.CollectionSpec.LoadAndAssign.
type hello_file_ring_bufferVariables struct {
}

// hello_file_ring_bufferPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadHello_file_ring_bufferObjects or ebpf.CollectionSpec.LoadAndAssign.
type hello_file_ring_bufferPrograms struct {
	CaptureOpenat *ebpf.Program `ebpf:"capture_openat"`
}

func (p *hello_file_ring_bufferPrograms) Close() error {
	return _Hello_file_ring_bufferClose(
		p.CaptureOpenat,
	)
}

func _Hello_file_ring_bufferClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed hello_file_ring_buffer_bpfeb.o
var _Hello_file_ring_bufferBytes []byte
